apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysqldbserver
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysqldbserver