apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
   app: appserver
spec:
  selector:
    app: appserver
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000