apiVersion: v1
kind: Pod
metadata:
  labels:
    app: appserver
  name:  web
spec:
  containers:
    - name: web
      image: 716654980616.dkr.ecr.us-east-1.amazonaws.com/assignment02-docker:v1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DBHOST
          value: "mysql.assignment2.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "123"
        - name: DBPORT
          value: "3306"
